image: python:3.11-bookworm
variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
cache:
    paths:
        - .cache/pip
before_script:
    - python --version ; pip --version # For debugging
    - pip install -rrequirements.devel.txt
qa:
    stage: test
    script:
        - ruff --version
        - ruff format --check
        - ruff check src/
test-build:
    stage: test
    script:
        - python -m build
